// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl_9OGwcrJigunpzP34gAK35bgRCteZQs',
    appId: '1:290410307664:web:9b4bd0ef3b48c85b277155',
    messagingSenderId: '290410307664',
    projectId: 'flutter-chat-1-14cf2',
    authDomain: 'flutter-chat-1-14cf2.firebaseapp.com',
    storageBucket: 'flutter-chat-1-14cf2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqvF8K5ZfuZEm0N8p6iyJCw5arn608w4Q',
    appId: '1:290410307664:android:e03e93475fda0994277155',
    messagingSenderId: '290410307664',
    projectId: 'flutter-chat-1-14cf2',
    storageBucket: 'flutter-chat-1-14cf2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBawbn_P6l1-mqlbT1Ry-8PfwCeYLiuv7U',
    appId: '1:290410307664:ios:d6e11f0523717463277155',
    messagingSenderId: '290410307664',
    projectId: 'flutter-chat-1-14cf2',
    storageBucket: 'flutter-chat-1-14cf2.appspot.com',
    iosClientId: '290410307664-p75d21u1e0okptlsuk5kh9b850dbdksr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBawbn_P6l1-mqlbT1Ry-8PfwCeYLiuv7U',
    appId: '1:290410307664:ios:d6e11f0523717463277155',
    messagingSenderId: '290410307664',
    projectId: 'flutter-chat-1-14cf2',
    storageBucket: 'flutter-chat-1-14cf2.appspot.com',
    iosClientId: '290410307664-p75d21u1e0okptlsuk5kh9b850dbdksr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppFirebase',
  );
}
